In [24]:
import numpy as np
class Kmeans:
    def __init__(self, k=3, iteration =1000, tol=1e-4 ):
        self.k = k
        self.iteration = iteration
        self.tol = tol

    def fit(self, X):
        # random init centroids
        self.centroids = X[np.random.choice(range(len(X)), self.k)]
        cluster_assign = np.zeros(len(X), dtype=int)

        for i in range(self.iteration):
            # find the closest distance centroids
            for j in range(len(X)):
                distances =  np.linalg.norm(X[j] - self.centroids, axis = 1)
                cluster_assign[j] = np.argmin(distances)
            
            prev_centroids = self.centroids.copy()

            # update the centroids
            for m in range(self.k):
                points = X[np.where(np.array(cluster_assign) == m)]
                
                if len(points)>0:
                    self.centroids[m] = np.mean(points, axis = 0)
            
            if np.allclose(prev_centroids, self.centroids, atol = self.tol):
                print(f"Converged after {i + 1} iterations")
                break

            prev_centroids = np.copy(self.centroids)
    
        self.cluster_assign = cluster_assign
    
    def predict(self, X):
        cluster_assign = np.zeros(len(X), dtype=int)
        for j in range(len(X)):
            distances =  np.linalg.norm(X[j] - self.centroids, axis = 1)
            cluster_assign[j] = np.argmin(distances)
        return cluster_assign
        



In [28]:
X = np.random.randn(5000,3)
k = 5
cluster = Kmeans(k)
cluster.fit(X)

Converged after 50 iterations


In [29]:
cluster_assignment = cluster.predict(X)
cluster_assignment[0:10]

array([0, 2, 0, 1, 1, 2, 4, 3, 4, 1])

## Experiment

In [1]:
points = [(1, 2), (1, 4), (1, 0), (10, 2), (10, 4), (10, 0)]
k = 2
initial_centroids = [(1, 1), (10, 1)]
max_iterations = 10

In [12]:
import numpy as np
X = np.array(points, dtype = np.float64)
initial_centroids = np.array(initial_centroids, dtype = np.float64)
m,n = X.shape
cluster_assignment = np.zeros(m)

In [17]:
for _ in range(max_iterations):
    for i in range(m):
        distances = np.linalg.norm(initial_centroids - X[i], axis =1)
        cluster_assignment[i] = np.argmin(distances)
    for j in range(k):
        cluster = X[np.where(cluster_assignment == j)]
        if len(cluster)>0:
            initial_centroids[j] = np.mean(cluster, axis=0)
    final_centroids = initial_centroids.copy()

In [18]:
initial_centroids

array([[ 1.,  2.],
       [10.,  2.]])

In [19]:
final_centroids

array([[ 1.,  2.],
       [10.,  2.]])

In [20]:
[tuple(row) for row in final_centroids.tolist()]

[(1.0, 2.0), (10.0, 2.0)]