In [42]:
import numpy as np

In [67]:
def simple_conv2d(input_matrix: np.ndarray, kernel: np.ndarray, padding: int, stride: int):

    # Extract Dimension
    input_height, input_width = input_matrix.shape
    kernel_height, kernel_width = kernel.shape

    # Apply padding to the input
    if padding > 0:
        padded = np.pad(input_matrix, pad_width=((padding, padding), (padding, padding)), mode='constant', constant_values=0)
    else:
        padded = input_matrix

    # Calculate output dimensions
    out_h, out_w =  (padded.shape[0] - kernel_height) //  stride + 1 , (padded.shape[1] - kernel_width) //  stride +1  

    # Init output array
    output_matrix = np.zeros((out_h, out_w))

    # Perform Convolution
    for i in range(out_h):
        for j in range(out_w):

            # Define the current region of interest
            region =  padded[i * stride : i * stride + kernel_height,  j * stride : j * stride + kernel_width]

            # Element-wise multiplication and sum
            output_matrix[i,j] = np.sum(region * kernel)
            
    return output_matrix

In [68]:
import numpy as np

input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2

output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

[[ 1.  1. -4.]
 [ 9.  7. -4.]
 [ 0. 14. 16.]]


In [69]:
input_matrix = np.array([ [1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.], [11., 12., 13., 14., 15.], [16., 17., 18., 19., 20.], [21., 22., 23., 24., 25.], ])
kernel = np.array([ [.5, 3.2], [1., -1.], ]) 
padding, stride = 2, 2 
output = simple_conv2d(input_matrix, kernel, padding, stride) 
print(output)

[[ 0.   0.   0.   0. ]
 [ 0.   5.9 13.3 12.5]
 [ 0.  42.9 50.3 27.5]
 [ 0.  80.9 88.3 12.5]]
