In [163]:
import numpy as np

In [199]:
def gradient_descent(X, y, weights, learning_rate, n_iterations, batch_size=1, method='batch'):
    m,n = X.shape
    loss_history = []
    
    ## init weight ##
    #weights = np.zeros(X.shape[1])
    for _ in range(n_iterations):
        # Calculate  Gradient 
        
        if method == 'batch':
            ## all data
            y_pred = X @ weights
            error = y_pred - y
            dw = (2/m) * (X.T @ error)
            weights = weights - learning_rate * dw
            
        elif method == 'stochastic':
            for i in range(m):
                Xi = X[i:i+1]
                yi = y[i : i+1]
                y_pred = Xi @ weights
                error = y_pred - yi
                #print(Xi)
                #print(Xi.T.shape)
                #print(error)
                dw = 2 * (Xi.T @ error)
                #print(dw)
                weights = weights - learning_rate * dw
                #print(weights)
                
        elif method == 'mini_batch':
            for start in range(0, m, batch_size):
                #start = i
                end = start + batch_size
                Xb = X[start : end]
                yb = y[start : end]
                y_pred = Xb @ weights
                error = y_pred - yb
                dw = (2/batch_size) * (Xb.T @ error)
                #print(dw)
                weights = weights - learning_rate * dw
                #print(weights)
        mse = np.mean((X @ weights - y) ** 2)
        loss_history.append(mse)
        
    return weights, loss_history

In [200]:
# Sample data
X = np.array([[1, 1], [2, 1], [3, 1], [4, 1]])
y = np.array([2, 3, 4, 5])

In [201]:
# Parameters
learning_rate = 0.01
n_iterations = 1000
batch_size = 2

In [202]:
# Initialize weights
weights = np.zeros(X.shape[1])

In [203]:
# Test Batch Gradient Descent
final_weights, loss_history = gradient_descent(X, y, weights, learning_rate, n_iterations, method='batch')

In [204]:
final_weights

array([1.01003164, 0.97050576])

In [212]:
#loss_history

In [206]:
# Test Stochastic Gradient Descent
final_weights, loss_history = gradient_descent(X, y, weights, learning_rate, n_iterations, method='stochastic')

In [207]:
final_weights

array([1.00000058, 0.99999813])

In [213]:
#loss_history

In [209]:
# Test Mini-Batch Gradient Descent
final_weights,  loss_history= gradient_descent(X, y, weights, learning_rate, n_iterations, batch_size, method='mini_batch')
final_weights

array([1.0003804 , 0.99883421])

In [211]:
loss_history[0:10]

[np.float64(6.368262934999999),
 np.float64(3.0268837414725356),
 np.float64(1.458835106291171),
 np.float64(0.7212012312210828),
 np.float64(0.3729472600376114),
 np.float64(0.2076212018747166),
 np.float64(0.1284696955368972),
 np.float64(0.09007391062196851),
 np.float64(0.07106181834900215),
 np.float64(0.06134218501235354)]