# Find the Image of a Matrix Using Row Echelon Form

## Task: Compute the Column Space of a Matrix
In this task, you are required to implement a function matrix_image(A) that calculates the column space of a given matrix A. The column space, also known as the image or span, consists of all linear combinations of the columns of A. To find this, you'll use concepts from linear algebra, focusing on identifying independent columns that span the matrix's image. Your task: Implement the function matrix_image(A) to return the basis vectors that span the column space of A. These vectors should be extracted from the original matrix and correspond to the independent columns.

In [3]:
import numpy as np

In [6]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
 Q, R = np.linalg.qr(A)

In [8]:
Q

array([[-0.12309149,  0.90453403,  0.40824829],
       [-0.49236596,  0.30151134, -0.81649658],
       [-0.86164044, -0.30151134,  0.40824829]])

In [9]:
R

array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -8.12021634e-16]])

In [10]:
np.diag(R)

array([-8.12403840e+00,  9.04534034e-01, -8.12021634e-16])

In [20]:
tol = 1e-10
rank = np.sum(np.abs(np.diag(R))>tol)

In [21]:
pivot_cols = np.where(np.abs(np.diag(R))>tol)[0]

In [22]:
pivot_cols

array([0, 1])

In [25]:
basis = A[:, pivot_cols[:rank]]
basis

array([[1, 2],
       [4, 5],
       [7, 8]])