# Convert Vector to Diagonal Matrix

### Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

In [1]:
import numpy as np

def make_diagonal(x):
	# Your code here
	#print(x)
	m = len(x)
	mat = np.zeros((m,m))
	for i in range(m):
		mat[i,i] = x[i]
	return mat

In [2]:
x = np.array([1, 2, 3])
output = make_diagonal(x)
print(output)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
