# Principal Component Analysis (PCA) Implementation


Write a Python function that performs Principal Component Analysis (PCA) from scratch. The function should take a 2D NumPy array as input, where each row represents a data sample and each column represents a feature. The function should standardize the dataset, compute the covariance matrix, find the eigenvalues and eigenvectors, and return the principal components (the eigenvectors corresponding to the largest eigenvalues). The function should also take an integer `k` as input, representing the number of principal components to return.

Sign Convention: Eigenvectors can point in either direction (if `v` is valid, so is `-v`). To ensure consistent results across different environments, apply this rule: for each eigenvector, find its first element with absolute value `> 1e-10`; if that element is negative, multiply the entire eigenvector by -1.

Note: Use `np.linalg.eigh` for eigendecomposition since covariance matrices are symmetric. This provides more numerically stable and consistent results than `np.linalg.eig`

In [44]:
import numpy as np

def pca(data: np.ndarray, k: int) -> np.ndarray:
    """
    Perform PCA and return the top k principal components.
    
    Args:
        data: Input array of shape (n_samples, n_features)
        k: Number of principal components to return
    
    Returns:
        Principal components of shape (n_features, k), rounded to 4 decimals.
        Each eigenvector's sign is fixed so its first non-zero element is positive.
    """
    # Your code here
    # pass
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0, ddof=1)
    data_standardized = (data - mean) / std
    n_samples = data_standardized.shape[0]
    covariance_matrix = (data_standardized.T @ data_standardized) / (n_samples - 1)
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)

    sorted_index = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_index]
    eigenvectors= eigenvectors[:, sorted_index]

    for i in range(eigenvectors.shape[1]):
        for j in range(eigenvectors.shape[0]):
            if abs(eigenvectors[j,i])>1e-10:
                if eigenvectors[j,i]<0:
                    eigenvectors[:, i] *= -1
                break
    priciple_component = eigenvectors[:,:k]
    return priciple_component

In [30]:
X = [[2.5, 2.4],
     [0.5, 0.7],
     [2.2, 2.9],
     [1.9, 2.2],
     [3.1, 3.0],
     [2.3, 2.7],
     [2.0, 1.6],
     [1.0, 1.1],
     [1.5, 1.6],
     [1.1, 0.9]]

In [31]:
import numpy as np
data = np.array(X)
data

array([[2.5, 2.4],
       [0.5, 0.7],
       [2.2, 2.9],
       [1.9, 2.2],
       [3.1, 3. ],
       [2.3, 2.7],
       [2. , 1.6],
       [1. , 1.1],
       [1.5, 1.6],
       [1.1, 0.9]])

In [32]:
mean = np.mean(data, axis=0)
std = np.std(data, axis=0, ddof=1)
data_standardized = (data - mean) / std
n_samples = data_standardized.shape[0]
covariance_matrix = (data_standardized.T @ data_standardized) / (n_samples - 1)

In [33]:
covariance_matrix

array([[1.        , 0.92592927],
       [0.92592927, 1.        ]])

In [34]:
eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)

In [35]:
eigenvalues

array([0.07407073, 1.92592927])

In [36]:
eigenvectors

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [37]:
sorted_indices = np.argsort(eigenvalues)[::-1]  # [::-1] reverses to descending
eigenvalues = eigenvalues[sorted_indices]
eigenvalues

array([1.92592927, 0.07407073])

In [38]:
eigenvectors = eigenvectors[:, sorted_indices]
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [39]:
#eigenvectors= np.array([[ 0.70710678, 0.70710678],
#       [ 0.70710678,  -0.70710678]])

In [40]:
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [41]:
for i in range(eigenvectors.shape[1]):
        # Find first element with absolute value > 1e-10
        for j in range(eigenvectors.shape[0]):
            if abs(eigenvectors[j, i]) > 1e-10:
                # If negative, flip the sign of entire eigenvector
                if eigenvectors[j, i] < 0:
                    eigenvectors[:, i] *= -1
                break

In [42]:
eigenvectors

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [43]:
eigenvectors[:,:1]

array([[0.70710678],
       [0.70710678]])

In [45]:
pca(data, 1)

array([[0.70710678],
       [0.70710678]])