# SVD of a 2x2 Matrix

Given a 2x2 matrix, write a Python function to compute its Singular Value Decomposition (SVD). The function should return matrices `U`, `s`, and `V` such that `A = U @ diag(s) @ V`.

Do not use numpy.linalg.svd or other built-in SVD functions.

Returns:

- `U`: 2x2 orthogonal matrix (left singular vectors)
- `s`: 1D array of 2 singular values (non-negative)
- `V`: 2x2 matrix (right singular vectors)

In [1]:
import numpy as np

def svd_2x2(A: np.ndarray) -> tuple:
    """
    Compute SVD of a 2x2 matrix.
    
    Args:
        A: 2x2 numpy array
    
    Returns:
        U: 2x2 orthogonal matrix (left singular vectors)
        s: 1D array of singular values
        V: 2x2 matrix (right singular vectors)
    """
    # Your code here
    #pass
    cov_mat = A.T @ A
    eigenvalues, eigenvectors = np.linalg.eigh(cov_mat)
    eigenvalues = np.maximum(eigenvalues, 0)
    singular_values = np.sqrt(eigenvalues)
    V = eigenvectors

    U = np.zeros((2,2))
    tol = 1e-10
    for i in range(2):
        if singular_values[i]> tol:
            U[:,i] = (A @ V[:,i])/singular_values[i]
        else:
            if i == 0:
                U[:, i] = np.array([1.0, 0.0])
            else:
                U[:, i] = np.array([-U[1, 0], U[0,0]]) # U[:,1] is orthogonal with U[:, 0]
                U[:, i] = U[:, i] / np.linalg.norm(U[:, i])
    
    sorted_indices = np.argsort(singular_values)
    singular_values = singular_values[sorted_indices]
    U = U [:, sorted_indices]
    V = V[:, sorted_indices]
    
    return U, singular_values, V

In [2]:
A = np.array([[-10, 8], [10, -1]])

In [3]:
U, s, V = svd_2x2(A)

In [4]:
U

array([[-0.6,  0.8],
       [-0.8, -0.6]])

In [5]:
s

array([ 4.47213595, 15.65247584])

In [6]:
V

array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]])

In [8]:
U, s, Vt = np.linalg.svd(A)
V = Vt.T

In [9]:
U

array([[-0.8,  0.6],
       [ 0.6,  0.8]])

In [10]:
V

array([[ 0.89442719,  0.4472136 ],
       [-0.4472136 ,  0.89442719]])

In [11]:
s

array([15.65247584,  4.47213595])