In [144]:
import numpy as np

## below both implementations of softmax is right

In [169]:
def softmax(x, axis = -1):
    x = x - np.max(x, axis = axis, keepdims = True)
    return np.exp(x) / np.sum(np.exp(x), axis = axis, keepdims =True)

In [170]:
def softmax(x, axis=-1):
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [173]:
def compute_qkv(X, W_q, W_k, W_v):
    q = X @ W_q
    k = X @ W_k
    v = X @ W_v
    return q, k, v

In [174]:

def self_attention(Q, K, V):
    def softmax(x, axis = -1):
        x = x - np.max(x, axis = axis, keepdims = True)
        return np.exp(x) / np.sum(np.exp(x), axis = axis, keepdims =True)
    attention = softmax(Q @ K.T * K.shape[-1]**(-0.5)) @ V
    return np.round(attention,6).tolist()

In [175]:
X = np.array([[1, 0], [0, 1]])
W_q = np.array([[1, 0], [0, 1]])
W_k = np.array([[1, 0], [0, 1]])
W_v = np.array([[1, 2], [3, 4]])

In [176]:
Q, K, V = compute_qkv(X, W_q, W_k, W_v)

In [177]:
Q

array([[1, 0],
       [0, 1]])

In [178]:
K

array([[1, 0],
       [0, 1]])

In [179]:
V

array([[1, 2],
       [3, 4]])

In [180]:
output = self_attention(Q, K, V)

In [181]:
output

[[1.660477, 2.660477], [2.339523, 3.339523]]

In [182]:
import numpy as np
X = np.array([[1, 1], [1, 0]]) 
W_q = np.array([[1, 0], [0, 1]])
W_k = np.array([[1, 0], [0, 1]]) 
W_v = np.array([[1, 2], [3, 4]]) 
Q, K, V = compute_qkv(X, W_q, W_k, W_v) 
output = self_attention(Q, K, V)

In [183]:
output

[[3.009285, 4.679046], [2.5, 4.0]]

In [184]:
import numpy as np 
X = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 0]]) 
W_q = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]]) 
W_k = np.array([[1, 1, 0], [0, 1, 1], [1, 0, 1]]) 
W_v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
Q, K, V = compute_qkv(X, W_q, W_k, W_v) 
output = self_attention(Q, K, V) 
print(output)

[[8.0, 10.0, 12.0], [8.619874, 10.619874, 12.619874], [7.380126, 9.380126, 11.380126]]
