In [1]:
import numpy as np

For Explanation see this [colab](https://taijusanagi.com/bernoulli-naive-bayes?utm_source=chatgpt.com)

In [11]:
class NaiveBayes():
    def __init__(self, smoothing=1.0):
        # Initialize smoothing
        #pass
        self.smoothing = smoothing
        #self.classes_ = np.array([0, 1])
        self.single_class = None # flag to check if only one class exists

    def forward(self, X, y):
        # Fit model to binary features X and labels y
        #pass
        nemails, nwords = X.shape
        unique_classes = np.unique(y)
        if len(unique_classes)==1:
            self.single_class = unique_classes[0]
            return self
        # Prior
        self.classes_ = np.unique(y)
        n_classes = np.bincount(y) 
        self.log_prior = np.log(n_classes/nemails)

        # Word Probability for each class
        word_present = np.array([X[y == 0].sum(axis = 0),
                X[y == 1].sum(axis = 0)])
        
        emails_per_class = n_classes.reshape(-1, 1) # vector to array
        # Laplace smoothing
        theta = (word_present + self.smoothing) / (emails_per_class + 2 * self.smoothing) 

        self.log_theta_present_ = np.log(theta)      # when word flag = 1
        self.log_theta_absent_  = np.log(1 - theta)  # when word flag = 0
        return self

    def predict(self, X):
        # Predict class labels for test set X
        # pass
        if self.single_class is not None:
            # Return only that class for all predictions
            return np.full(X.shape[0], self.single_class)

        score = self.log_prior + X @ self.log_theta_present_.T + (1 - X) @ self.log_theta_absent_.T
        return self.classes_[score.argmax(axis =1)]

In [12]:
X = np.array([[1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0], [1, 1, 1]])
y = np.array([1, 1, 0, 0, 1])

In [13]:
np.unique(y)

array([0, 1])

In [14]:
yyy = np.array([1, 1, 1])

In [15]:
np.unique(yyy)

array([1])

In [16]:
model = NaiveBayes(smoothing=1.0)

In [17]:
model.forward(X, y)

In [18]:
model.predict(np.array([[1, 0, 1]]))

array([1])

In [19]:
import numpy as np 
model = NaiveBayes(smoothing=1.0) 
X = np.random.randint(0, 2, (10, 3)) 
y = np.zeros(10) 
model.forward(X, y) 
X_test = np.random.randint(0, 2, (3, 3)) 
print(model.predict(X_test))

[0. 0. 0.]


In [ ]:
import numpy as np
X = np.array([[1, 0, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0], [1, 1, 1]])
y = np.array([1, 1, 0, 0, 1])

In [ ]:
classes_ = np.array([0, 1]) 

In [ ]:
# Calculate theta
nemails, nwords = X.shape
classes = np.array([0,1])
# Prior
n_classes = np.bincount(y) 
log_prior = np.log(n_classes/nemails)

In [ ]:
n_classes

In [ ]:
log_prior

In [ ]:
# Word Probability for each class

In [ ]:
X[y == 0].sum(axis = 0)

In [ ]:
X[y == 1].sum(axis = 0)

In [ ]:
word_present = np.array([X[y == 0].sum(axis = 0),
                X[y == 1].sum(axis = 0)])

In [ ]:
word_present

In [ ]:
emails_per_class = n_classes.reshape(-1, 1)
emails_per_class

In [ ]:
emails_per_class + 2

In [ ]:
alpha = 1
theta = (word_present + alpha) / (emails_per_class + 2 * alpha)

In [ ]:
theta

In [ ]:
theta.shape

In [ ]:
X.shape

In [ ]:
log_theta_present_ = np.log(theta)      # when word flag = 1
log_theta_absent_  = np.log(1 - theta)  # when word flag = 0

In [ ]:
log_theta_present_

In [ ]:
log_theta_absent_

In [ ]:
score = log_prior + X @ log_theta_present_.T + (1 - X) @ log_theta_absent_.T

In [ ]:
score

In [ ]:
score.argmax(axis =1 )

In [ ]:
score.argmax(axis = 0 )

In [ ]:
classes[score.argmax(axis =1 )]

In [ ]:
X = np.array([[1, 0, 1]])


In [ ]:
score = log_prior + X @ log_theta_present_.T + (1 - X) @ log_theta_absent_.T

In [ ]:
score

In [ ]:
classes[score.argmax(axis =1 )]