In [1]:
import numpy as np

In [44]:
def topk(H: np.ndarray, k: int) -> np.ndarray:
        """
        For each row in matrix H, keeps the top-k values and sets the rest to -inf.
    
        Args:
            H (np.ndarray): Input 2D array of shape (batch_size, num_experts)
            k (int): Number of top elements to keep per row
    
        Returns:
            np.ndarray: Same shape as H, with only top-k elements kept and rest set to -inf
        """
        # Copy H to avoid modifying the original
        H_topk = np.full_like(H, -np.inf)  # Initialize with -inf
    
        # Get indices of top-k elements in each row
        topk_indices = np.argpartition(-H, kth=k-1, axis=1)[:, :k]  # partial sort
    
        # Assign top-k values to their positions
        for i in range(H.shape[0]):
            H_topk[i, topk_indices[i]] = H[i, topk_indices[i]]
    
        return H_topk

In [48]:
def noisy_topk_gating(
    X: np.ndarray,
    W_g: np.ndarray,
    W_noise: np.ndarray,
    N: np.ndarray,
    k: int
) -> np.ndarray:
    
    H_base = X @ W_g
    H_noise = X @ W_noise
    softplus = np.log1p(np.exp(H_noise))
    H = H_base + N * softplus
    masked_H = topk(H,k)
    exp = np.exp( masked_H - np.max(masked_H, axis = 1, keepdims = True))
    return exp / np.sum(exp)

In [49]:
X = np.array([[1.0, 2.0]])
W_g = np.array([[1.0, 0.0], [0.0, 1.0]])
W_noise = np.array([[0.5, 0.5], [0.5, 0.5]])
N = np.array([[1.0, -1.0]])
k = 2

In [50]:
noisy_topk_gating(X, W_g, W_noise, N, k)

array([[0.91704259, 0.08295741]])

In [39]:
H_base = X @ W_g
H_noise = X @ W_noise

In [40]:
H_base

array([[1., 2.]])

In [29]:
H_noise

array([[1.5, 1.5]])

In [30]:
softplus = np.log1p(np.exp(H_noise))
softplus

array([[1.70141328, 1.70141328]])

In [31]:
H = H_base + N * softplus
H

array([[2.70141328, 0.29858672]])

In [42]:
masked_H = topk(H, k)
masked_H

array([[2.70141328, 0.29858672]])

In [18]:
def topk(H: np.ndarray, k: int) -> np.ndarray:
    """
    For each row in matrix H, keeps the top-k values and sets the rest to -inf.

    Args:
        H (np.ndarray): Input 2D array of shape (batch_size, num_experts)
        k (int): Number of top elements to keep per row

    Returns:
        np.ndarray: Same shape as H, with only top-k elements kept and rest set to -inf
    """
    # Copy H to avoid modifying the original
    H_topk = np.full_like(H, -np.inf)  # Initialize with -inf

    # Get indices of top-k elements in each row
    topk_indices = np.argpartition(-H, kth=k-1, axis=1)[:, :k]  # partial sort

    # Assign top-k values to their positions
    for i in range(H.shape[0]):
        H_topk[i, topk_indices[i]] = H[i, topk_indices[i]]

    return H_topk

In [32]:
masked_H = topk(H, k)
masked_H

array([[2.70141328, 0.29858672]])

In [33]:
exp = np.exp( masked_H - np.max(masked_H, axis = 1, keepdims = True))
exp

array([[1.       , 0.0904619]])

In [34]:
exp / np.sum(exp)

array([[0.91704259, 0.08295741]])

In [35]:
H_topk = np.full_like(H, -np.inf)
H_topk

array([[-inf, -inf]])

In [36]:
topk_indices = np.argpartition(-H, kth=k-1, axis=1)[:, :k]  # partial sort
topk_indices

array([[0, 1]])